name: GatherVoice
favicon: null
layout_spectrum: 0.59756
typography_spectrum: 0.2668
title: Dedicated to User Centred Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#361772'
    - '#5a3b96'
    - '#ffffff'
    - '#7e6aa4'
    - '#ad9eca'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
