name: GatherVoice
favicon: null
layout_spectrum: 0.59756
typography_spectrum: 0.2668
title: Dedicated to User Centred Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#49577a'
    - '#2b3346'
    - '#e3b9a9'
    - '#b08272'
  brandStrength: 0.875
  lightness: 0.4583242100197822
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
